# Generated by Django 4.1.4 on 2022-12-11 22:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CashInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cash_at_hand', models.IntegerField()),
                ('expenditure', models.IntegerField()),
                ('revenue', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.CharField(blank=True, max_length=150, null=True, unique=True)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('quantity_per_pack', models.IntegerField(blank=True, max_length=255, null=True)),
                ('quantity_per_unit', models.IntegerField(blank=True, max_length=255, null=True)),
                ('price_per_quantity', models.IntegerField()),
                ('price_per_unit', models.IntegerField()),
                ('category', models.CharField(choices=[('minerals', 'MINERALS'), ('groceries', 'GROCERIES'), ('foodstuff', 'FOODSTUFF')], max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_purchased', models.IntegerField()),
                ('price', models.IntegerField()),
                ('amount_paid', models.IntegerField()),
                ('change_given', models.IntegerField()),
                ('date_purchased', models.DateTimeField()),
                ('restock', models.BooleanField()),
                ('purchased_by', models.CharField(max_length=255)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='inventory.product')),
            ],
        ),
    ]
