# Generated by Django 4.1.4 on 2022-12-11 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='quantity_per_pack',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='quantity_per_unit',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
