# Generated by Django 4.1.4 on 2022-12-12 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_product_quantity_per_pack_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchase',
            old_name='quantity_purchased',
            new_name='quantity_per_pack',
        ),
        migrations.AddField(
            model_name='purchase',
            name='quantity_per_unit',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='date_purchased',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='purchased_by',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
