# Generated by Django 4.1.4 on 2022-12-12 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_rename_quantity_purchased_purchase_quantity_per_pack_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='quantity_per_pack',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='quantity_per_unit',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
